/**
 * Login Actions
 */
export const AUTH_INPUT_CHANGE = "AUTH_INPUT_CHANGE";
export const AUTH_ERROR_CHANGE = "AUTH_ERROR_CHANGE";
export const AUTH_SHOW_LOADER = "AUTH_SHOW_LOADER";
export const AUTH_HIDE_LOADER = "AUTH_HIDE_LOADER";
export const AUTH_ALERT_MESSAGE = "AUTH_ALERT_MESSAGE";

/**
 * Loading
 */
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

/***
 * Applications
 */

export const SET_USER_AUTHORIZATION_MENUS = "SET_USER_AUTHORIZATION_MENUS";
export const SET_USER_INFO = "SET_USER_INFO";
export const SHOW_USER_PROFILE = "SHOW_USER_PROFILE";
export const HIDE_USER_PROFILE = "HIDE_USER_PROFILE";
export const MENU_ITEM_CLICK = "MENU_ITEM_CLICK";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const MENU_ACTIVE_ITEM_CHANGE = "MENU_ACTIVE_ITEM_CHANGE";

/**
 * Page Actions
 */
export const PAGE_INPUT_CHANGE = "PAGE_INPUT_CHANGE";

export const SET_PAGE_EDIT_DATA = "SET_PAGE_EDIT_DATA";
export const SET_PAGE_EDIT_DATA_FULLFILLED = "SET_PAGE_EDIT_DATA_FULLFILLED";
export const SET_PAGE_EDIT_DATA_REJECTED = "SET_PAGE_EDIT_DATA_REJECTED";

export const PAGE_FORM_ERROR_CHANGE = "PAGE_FORM_ERROR_CHANGE";
export const PAGE_FORM_SHOW_LOADER = "PAGE_FORM_SHOW_LOADER";
export const PAGE_FORM_HIDE_LOADER = "PAGE_FORM_HIDE_LOADER";

export const PAGE_MODAL = "PAGE_MODAL";
export const PAGE_MODAL_SHOW = "PAGE_MODAL_SHOW";
export const PAGE_MODAL_HIDE = "PAGE_MODAL_HIDE";

export const PAGE_FORMDATA_CLEAN = "PAGE_FORMDATA_CLEAN";

/**
 * app site list
 */
export const SET_CHANNEL_LIST = "SET_CHANNEL_LIST";
export const SET_CHANNEL_LIST_FULLFILLED = "SET_CHANNEL_LIST_FULLFILLED";
export const SET_CHANNEL_LIST_REJECTED = "SET_CHANNEL_LIST_REJECTED";

export const SET_DAY_LIST = "SET_DAY_LIST";
export const SET_DAY_LIST_FULLFILLED = "SET_DAY_LIST_FULLFILLED";
export const SET_DAY_LIST_REJECTED = "SET_DAY_LIST_REJECTED";

export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const SET_CATEGORY_LIST_FULLFILLED = "SET_CATEGORY_LIST_FULLFILLED";
export const SET_CATEGORY_LIST_REJECTED = "SET_CATEGORY_LIST_REJECTED";
